version: '3'

services:
  alpaca:
    image: python:3.10
    container_name: alpaca
    stdin_open: true
    tty: true
    environment:
      - TRANSFORMERS_CACHE=/app/.cache
    command: /bin/bash -c "cd /app && ./run.sh"
    ports:
      - 6006:6006
    volumes:
      - .:/app
      - ./.site-packages:/usr/local/lib/python3.10/site-packages
    tmpfs:
      - /tmp